#!/bin/bash

git config --global user.name "Michael Tews"
git config --global user.email michael@tews.dev
git config --global user.gpgsign true
git config --global user.signingkey 0512FA62963CFD20
git config --global commit.gpgsign true
