- name: configure arch 
  hosts: localhost
  tasks:
    - name: update
      community.general.pacman:
        update_cache: yes
        upgrade: yes
    - name: base
      community.general.pacman:
        update_cache: yes
        name:
          - git
          - base-devel
          - neovim
          - code
          - yadm
          - ripgrep
          - zsh
          - btop
          - ttf-firacode-nerd
          - noto-fonts
          - noto-fonts-cjk
          - noto-fonts-emoji
          - noto-fonts-extra
          - power-profiles-daemon
          - rustup
          - zsh-autosuggestions
          - tmux
          - snapper
          - go
          - fzf
          - lazygit
          - mpv
          - docker
          - ffmpeg
          - npm
          - marksman
          - vale
          - fd
          - zsh-syntax-highlighting
          - less
          - tldr
          - man
          - maven
          - jdtls
          - hugo
          - typescript-language-server
          - lua-language-server
          - markdownlint
    - name: desktop 
      community.general.pacman:
        update_cache: yes
        name:
          - bluez
          - v4l2loopback-dkms
          - cups
          - gnome-disk-utility
          - virt-manager
          - qemu-full
          - nftables
          - chromium
          - bluez-utils
          - blueman
          - xdg-user-dirs
          - sway
          - bemenu-wayland
          - bemenu
          - grim
          - brightnessctl
          - polkit
          - polkit-gnome
          - slurp
          - waybar
          - networkmanager
          - network-manager-applet
          - mako
          - xdg-desktop-portal
          - xdg-desktop-portal-wlr
          - firefox
