# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  hardware.wirelessRegulatoryDatabase = true;
  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="DE"
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bbc2bdd1-a84e-41b0-9b9d-1e47bbd11ca8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices = {
    "luks-3f063168-3a99-4661-bfab-b01b26a5a6da".device =
      "/dev/disk/by-uuid/3f063168-3a99-4661-bfab-b01b26a5a6da";
    "luks-5730996-b870-4f4c-8683-1864e8ab010b".device =
      "/dev/disk/by-uuid/f5730996-b870-4f4c-8683-1864e8ab010b";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0128-1967";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/8f8d5435-1ca6-4f20-9f86-f5c326b21f47"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
